### ISSUE TITLE
Add Repository License

### ISSUE THREAD

**Issue by danieljimeneznz** [projectestac/moodle-local_oauth#15]
Hello, I'm currently looking at implementations of Moodle Oauth plugins and yours seems to be a solid option.
I would like to use/fork it for one of the tasks in my organization, however there is no license available for the repository and per GitHub policies it is considered to be a proprietary code that disallows such usage.

>You're under no obligation to choose a license. However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work.

Would it be possible for one of the maintainers to clarify that it is indeed possible to use your project and if possible add license of choice to repository so that there is no misunderstandings regarding it.
Thank you!

**Comment by toniginard** [comment]
Hi Daniel,

You're right: we're missing the license file, although it is possible to find some references in some files.

All the code in this repository is licensed under GPL v3, excluding the third party library which is MIT (https://github.com/bshaffer/oauth2-server-php/).

This code is also released as a component of the Àgora project, which is also GPL v3.


Best wishes!
