### ISSUE TITLE
Login to Moodle

### ISSUE THREAD

**Issue by mhussain001** [projectestac/moodle-local_oauth#4]
Hello

Thanks for publishing the plugin, it looks good.

I have a question regarding the redirection, after successful login when user goto moodle page will user be logged in or he needs to login again?

Regards
Hussain

**Comment by sarjona** [comment]
Hi @mhussain001 !

This system has SSO so if the user is logged, it won't be necessary to login again ;-)

Best wishes from Barcelona
Sara
