### ISSUE TITLE
OpenID Connect

### ISSUE THREAD

**Issue by cwarwicker** [projectestac/moodle-local_oauth#7]
Hi,

We are trying to integrate authentication to another system through Moodle and I came across your plugin.

The other system (xwiki) only supports the use of OpenID Connect, though an extension, not just a simple OAuth 2 workflow, so we've been unable to make them play nicely, as the xwiki site is requesting scopes that moodle/local_oauth doesn't support, e.g. `openid profile email address phone`

Are you aware of any way to make this plugin work with oidc?

Thanks.

**Comment by toniginard** [comment]
Hi!

We have no plans to extend this plugin. We only do maintenance in order to keep it working with our Moodle version.



Best wishes
