### ISSUE TITLE
I found a little typo

### ISSUE THREAD

**Issue by bemtorres** [projectestac/moodle-local_oauth#8]
Hi.
I found a little typo in the Spanish translation

Está seguro que quiere **eleminar** el cliente {$a}
It should be "eliminar" instead

https://github.com/projectestac/moodle-local_oauth/blob/b1c71e53e99e1708bb1dc728c7c31699e14ab01b/lang/es/local_oauth.php#L27

**Comment by monicagrau** [comment]
Thanks for the notice, we will integrate the change as soon as possible.
